-- HARDWARE-------------------------------------------------------------------------------------------------------------
CREATE TABLE HARDWARE
(
  ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
  VERSION LONG,
  HARDWARE_TYPE_ID LONG,
  PRICE DECIMAL,
  PURCHASE_DATE DATE,
  SERIAL_NUMBER LONG
);

-- HARDWARE_TYPE -------------------------------------------------------------------------------------------------------
CREATE TABLE HARDWARE_TYPE
(
  ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
  VERSION LONG,
  TYPE VARCHAR(255)
);

-- HARDWARE_TRANSACTION_TYPE -------------------------------------------------------------------------------------------
CREATE TABLE HARDWARE_TRANSACTION_TYPE
(
  ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
  VERSION LONG,
  TYPE VARCHAR(255),
);

-- HARDWARE_TRANSACTION ------------------------------------------------------------------------------------------------
CREATE TABLE HARDWARE_TRANSACTION
(
  ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
  VERSION LONG,
  HARDWARE_ID LONG,
  PERSON_ID LONG,
  HARDWARE_TRANSACTION_TYPE_ID LONG,
  TRANSACTION_DATE DATE
);


-- PERSON --------------------------------------------------------------------------------------------------------------
CREATE TABLE PERSON
(
  ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
  VERSION LONG,
  FIRST_NAME VARCHAR (255),
  LAST_NAME VARCHAR (255),
  EMAIL VARCHAR (255),
  USERNAME VARCHAR (255)
);

-- BUDGET_TRANSACTION --------------------------------------------------------------------------------------------------
CREATE TABLE BUDGET_TRANSACTION
(
  ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PERSON_ID LONG,
  VERSION LONG,
  INPUT_AMOUNT DECIMAL,
  OUTPUT_AMOUNT DECIMAL,
  TRANSACTION_DATE DATE,
);

-- POSITION ------------------------------------------------------------------------------------------------------------
CREATE TABLE POSITION
(
  ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
  VERSION LONG,
  POSITION VARCHAR(255)
);

-- BUDGET --------------------------------------------------------------------------------------------------------------
CREATE TABLE BUDGET
(
  ID LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
  VERSION LONG,
  AMOUNT DECIMAL
);

-- HARDWARE_BUDGET_TRANSACTION -----------------------------------------------------------------------------------------
CREATE TABLE HARDWARE_BUDGET_TRANSACTION
(
  HARDWARE_ID LONG,
  VERSION LONG,
  BUDGET_TRANSACTION_ID LONG
);

-- PERSON_POSITION -----------------------------------------------------------------------------------------------------
CREATE TABLE PERSON_POSITION
(
  PERSON_ID LONG,
  POSITION_ID LONG,
  VALID_FROM DATE null,
  VALID_TO DATE null,
  VERSION LONG
);

-- BUDGET_POSITION -----------------------------------------------------------------------------------------------------
CREATE TABLE BUDGET_POSITION
(
  BUDGET_ID LONG,
  POSITION_ID LONG,
  VALID_FROM Date null,
  VALID_TO Date null,
  VERSION LONG

);

ALTER TABLE HARDWARE_TRANSACTION
  ADD CONSTRAINT HARDWARE_TRANSACTION_PERSON__fk
FOREIGN KEY (PERSON_ID) REFERENCES PERSON;

ALTER TABLE HARDWARE_TRANSACTION
  ADD CONSTRAINT HARDWARE_TRANSACTION_HARDWARE__fk
FOREIGN KEY (HARDWARE_ID) REFERENCES HARDWARE;

ALTER TABLE HARDWARE
  ADD CONSTRAINT HARDWARE_HARDWARE_TYPE__fk
FOREIGN KEY (HARDWARE_TYPE_ID) REFERENCES HARDWARE_TYPE;

ALTER TABLE HARDWARE_TRANSACTION
  ADD CONSTRAINT HARDWARE_TRANSACTION_HARDWARE_TRANSACTION_TYPE__fk
FOREIGN KEY (HARDWARE_TRANSACTION_TYPE_ID) REFERENCES HARDWARE_TRANSACTION_TYPE;

ALTER TABLE BUDGET_TRANSACTION
  ADD CONSTRAINT BUDGET_TRANSACTION_PERSON__fk
FOREIGN KEY (PERSON_ID) REFERENCES PERSON;

ALTER TABLE HARDWARE_BUDGET_TRANSACTION
  ADD CONSTRAINT HARDWARE_BUDGET_TRANSACTION_BUDGET_TRANSACTION__fk
FOREIGN KEY (BUDGET_TRANSACTION_ID) REFERENCES BUDGET_TRANSACTION;

ALTER TABLE HARDWARE_BUDGET_TRANSACTION
  ADD CONSTRAINT HARDWARE_BUDGET_TRANSACTION_HARDWARE__fk
FOREIGN KEY (HARDWARE_ID) REFERENCES HARDWARE;

ALTER TABLE BUDGET_POSITION
ADD CONSTRAINT BUDGET_POSITION_BUDGET__fk
FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET;

ALTER TABLE BUDGET_POSITION
ADD CONSTRAINT BUDGET_POSITION_POSITION__fk
FOREIGN KEY (POSITION_ID) REFERENCES POSITION;

ALTER TABLE PERSON_POSITION
ADD CONSTRAINT PERSON_POSITION_PERSON__fk
FOREIGN KEY (PERSON_ID) REFERENCES PERSON;

ALTER TABLE PERSON_POSITION
ADD CONSTRAINT PERSON_POSITION_POSITION__fk
FOREIGN KEY (POSITION_ID) REFERENCES POSITION;

-- ALTER TABLE POSITION
--   ADD CONSTRAINT POSITION_BUDGET__fk
-- FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET;

-- CREATE TABLE BUDGET_TRANSACTION_TYPE
-- (
--   ID LONG PRIMARY KEY,
--   TYPE VARCHAR(255),
-- );

-- ALTER TABLE BUDGET_TRANSACTION
--   ADD CONSTRAINT BUDGET_TRANSACTION_BUDGET_TRANSACTION_TYPE__fk
-- FOREIGN KEY (BUDGET_TRANSACTION_TYPE_ID) REFERENCES BUDGET_TRANSACTION_TYPE;

--
-- ALTER TABLE PERSON
--   ADD CONSTRAINT PERSON_POSITION_ID__fk
-- FOREIGN KEY (POSITION_ID) REFERENCES POSITION;